### ISSUE TITLE
Непонятные цифры в конце ссылки

### ISSUE THREAD

**Issue by R4M5EY** [Kirlovon/Tape-Operator#41]
https://tapeop.dev/?movie=619322075 - вот допустим фильм 12-я неудача, в плеере имеет число 619322075, хотя на КиноПоиске у него 5356479. Нигде нет данного числа, ни imdb, letterboxd, kp и тд. 
Раньше что было удобно, с мобилы открыл КП, нашел нужный фильм, запомнил число и поменял их в сохранненой вкладке с плеером на нужное и все, смотришь спокойно фильм 

(Вот пример:
https://www.kinopoisk.ru/film/5356479/ - число на КП
https://kinopoisk-watch-dsze5.ondigitalocean.app/player/?id=5356479 - число в плеере по старой ссылке
https://tapeop.dev/?movie=619322075 - число по новой

**Comment by Kirlovon** [comment]
Все так, это одно из внесенных изменений. Эта цифра - уникальный хеш фильма, который генерируется индивидуально для браузера. Ссылка будет работать только в том браузере, в котором был открыт фильм с помощью скрипта, её нельзя отправить кому либо.

Ранее, Kinopoisk Watch позволял свободно делиться ссылками на плеер c фильмом. Ссылки на плеер начали распространяться на сторонних ресурсах, а я начал получать жалобы на распространение пиратского контента. Так что это скорее вынужденное изменение для предотвращения этого.  🥲

Для просмотра фильмовы с телефона, могу посоветовать установить скрипт на телефон с помощью [Userscripts](https://apps.apple.com/us/app/userscripts/id1463298887) (для IOS), либо [Firefox](https://play.google.com/store/apps/details?id=org.mozilla.firefox)  (для Android), на который можно установить Tempermonkey.

**Comment by monolit** [comment]
да это печально
