### ISSUE TITLE
В хедере не корректная название звковой дорожки

### ISSUE THREAD

**Issue by aliksadykov** [Kirlovon/Tape-Operator#42]
1. Запускаешь фильм, с дефолтной аудио дорожкой - плеер Алоха
2.  разворачиваешь фулскрин
3. через шестеренку меняешь аудиодорожку
4. сворачиваешь в стандартный размер окна
5. сверху указана дефолтная акудиодорожка

**Comment by Kirlovon** [comment]
Это баг плеера Aloha, не могу его исправить

**Comment by LoveCaxarok** [comment]
плеер Aloha → шестеренка → сообщить об ошибке
