### ISSUE TITLE
Визуальный баг при полноэкранном режиме

### ISSUE THREAD

**Issue by RekonSuper** [Kirlovon/Tape-Operator#43]
В момент когда делаешь полноэкранный режим проподают все элементы интерфейса (старт/стоп, настройки, плеер и т.д.). Примечание, функционал остаётся но не видны сами иконки. Появляется этот баг только в польноэкранном режиме и когда фильм/сериал идёт, при паузе интерфейс появляется.

**Comment by Bokk0** [comment]
Звучит как проблема конкретного плеера
Так что это не сюда

**Comment by Kirlovon** [comment]
В каком именно плеере эта проблема? Я не отвечаю за интерфейс каждого из плееров, так что скорее всего не смогу исправить это.
