### ISSUE TITLE
Поддержка мобильной версии IMDB, "Episode list"

### ISSUE THREAD

**Issue by Bokk0** [Kirlovon/Tape-Operator#44]
Нет поддержки мобильной веб версии имдб
Ссылка для примера: https://m.imdb.com/title/tt2887954/
![Screenshot_20240727-133636](https://github.com/user-attachments/assets/26266284-a6e3-450a-af0a-d8c5758966b8) ![Screenshot_20240727-133812](https://github.com/user-attachments/assets/a10d7c24-e841-47ec-9bcd-8714d4f53830)

------

Если переходить со страницы эпизодов https://www.imdb.com/title/tt2887954/episodes/)
То на страничке плеера будет лишний текст 
![Screenshot_20240727-134031~2](https://github.com/user-attachments/assets/86ed3d9f-f0af-4e73-a9fb-2eb36c255fb1)

**Comment by Kirlovon** [comment]
Спасибо за наводку! Исправил это в коммите [ec30142](https://github.com/Kirlovon/Tape-Operator/commit/ec3014274456aa5e5d4f1c9490e07c56220e3e0c). Обновите скрипт, чтобы изменения вступили в силу!
