### ISSUE TITLE
В Safari на iOS некорректно отображается полоска

### ISSUE THREAD

**Issue by kda2495** [Kirlovon/Tape-Operator#45]
При использовании Userscripts в Safari полоска появляется, но выглядит не так, как на ПК.
iOS 15, iPhone SE 2016 (просто для примера, на других проверить пока не могу)
![photo_5371003723914010771_y](https://github.com/user-attachments/assets/3cdc67bf-8127-420c-9a65-d2ad0698daf3)

**Comment by Kirlovon** [comment]
Проверил на Safari в iPhone 15, всё ок. Похоже, проблема только в старых версиях Safari, и связана с CSS (грань изображения видна с левой стороны, так что оно отрисовывается). Может, кто-то знает, в чём дело? У меня нет устройства для проверки.

**Comment by kda2495** [comment]
> Проверил на Safari в iPhone 15, всё ок. Похоже, проблема только в старых версиях Safari, и связана с CSS (грань изображения видна с левой стороны, так что оно отрисовывается). Может, кто-то знает, в чём дело? У меня нет устройства для проверки.

Да, проверил на iPhone 13 mini с iOS 16 и все отлично. Ладно, не стоит тратить силы на исправление этого, главное, что работает. Спасибо Вам!
