### ISSUE TITLE
не показывает "ярлык" на плеер на themoviedb.org/tv/

### ISSUE THREAD

**Issue by LeonMskRu** [Kirlovon/Tape-Operator#46]
https://www.themoviedb.org/tv/253336?language=en-US
пробовал и firefox и brave
![image](https://github.com/user-attachments/assets/4f6b4a98-0a8d-48d3-8906-1a0bf2f66e7c)

https://www.imdb.com/title/tt32263592/
![image](https://github.com/user-attachments/assets/358e1089-57ce-4a34-a7db-92eabd9ee9e4)

**Comment by Kirlovon** [comment]
Спасибо за репорт! Исправил в https://github.com/Kirlovon/Tape-Operator/commit/ada50dc3d7037443764d7c041b38cb2170e972b1, обновите скрипт что бы изменения вступили в силу!
