### ISSUE TITLE
Tape Operator не работает

### ISSUE THREAD

**Issue by LoveCaxarok** [Kirlovon/Tape-Operator#47]
![112233](https://github.com/user-attachments/assets/3b0e5dab-f0fc-4338-a74c-a34c1f680326)

**Comment by Kirlovon** [comment]
Это была временная ошибка связанная с нерабочим API Kinobox. На данный момент все должно работать.

**Comment by LoveCaxarok** [comment]
@Kirlovon Это ошибка до сих пор есть ,я её решил тем что включил VPN,но включать каждый раз VPN чисто мое мнение это как мутарно,ещё к этому видео подвисает.
