### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by 1NXXXN1** [Kirlovon/Tape-Operator#48]
![{C2D3BB44-4ACA-451D-8FFD-54D71389F64F}](https://github.com/user-attachments/assets/ca07bcaf-5222-47e0-82d8-1d09556f98a4)

**Comment by Kirlovon** [comment]
Если я правильно понял, это отредактированная вами версия плеера. Не знаю, в чем конкретно может быть проблема, но она явно связана с вашими изменениями.
