### ISSUE TITLE
Как добавить страну после названия фильма? 

### ISSUE THREAD

**Issue by 1NXXXN1** [Kirlovon/Tape-Operator#49]
![image](https://github.com/user-attachments/assets/e2dc4965-0b2a-4878-a028-00517acb0982)

**Comment by Kirlovon** [comment]
Этот текст берется из мета-тега `og:title` или заголовка страницы, с которой открыт фильм. Чтобы отображать страну фильма, нужно модифицировать скрипт, чтобы он мог извлекать информацию о стране с страницы фильма. Я пока не собираюсь добавлять эту функцию, но вы можете попробовать сделать это сами.

**Comment by 1NXXXN1** [comment]
`og:title` надо сменить на другой значений как на рисунке
![image](https://github.com/user-attachments/assets/c6bec231-cc85-46d9-9015-263e11df1b25)
или какой, не подскажете?

**Comment by Kirlovon** [comment]
Это зависит от страницы, с которой открывается плеер. Например, на КиноПоиске страна производства фильма хранится в элементе, доступном через ⁠`document.querySelector('*[data-tid="d5ff4cc"]').textContent`. Попробуйте отправить эту переменную вместе с названием фильма.
