### ISSUE TITLE
Хочешь собрать все деньги?)

### ISSUE THREAD

**Issue by 3d3d3d360** [Kirlovon/Tape-Operator#50]
Реклама через каждые 3-8 минут. Реклама одинаковая. Посмотри 8 серий сериала и у тебя поедет крыша. Это раньше так было, а сейчас реклама останавливается и пока не нажмешь на экран, чтобы запустился сайт рекламодателя в новом окне, продолжение показа фильма не будет. Разраб, ты полное дерьмо, но раньше это было не так

**Comment by 1NXXXN1** [comment]
Используйте adblock

**Comment by LoveCaxarok** [comment]
ublock origin в помощь

**Comment by monolit** [comment]
АХАХАХ легендарные ответы

**Comment by Kirlovon** [comment]
@3d3d3d360 Количество рекламы контролируется источниками фильмов (Aloha, Collaps итд), так что это не моя вина. Я не разу не получал каких либо денег с этого сервиса, и не собираюсь. Я просто делаю скрипт который делает просмотр фильмов более удобным.

**Comment by Kirlovon** [comment]
Рекомендую установить uBlock Origin и больше не жаловаться на и так бесплатный сервис. 😉
