### ISSUE TITLE
Альтернативную версию скрипта

### ISSUE THREAD

**Issue by LoveCaxarok** [Kirlovon/Tape-Operator#51]
Будет ли альтернативную версию скрипта как была при Kinopoisk Watsh? А то прощатьтся с Tape Operator как то не хочется.Ещё странно ,то что изначально когда появился Tape Operator все нормально работало ,а вот недавно Tape Operator перестал работать,работает только с VPN ,теперь.
![image](https://github.com/user-attachments/assets/cb85ddc5-c282-41ba-a5d5-ed5b4930d40f)

**Comment by Kirlovon** [comment]
Привет! Странно, вроде как Kinobox API все еще должен работать. Могли бы ли вы показать вкладку Network, а именно запрос к kinobox.tv?

**Comment by LoveCaxarok** [comment]
@Kirlovon 
![image](https://github.com/user-attachments/assets/2ac834b4-c243-45a1-ae73-629a6f82f144)
![image](https://github.com/user-attachments/assets/319f8209-d888-47fb-94f8-059b5613a830)
![image](https://github.com/user-attachments/assets/ed265ee2-ac4a-430f-8c60-87d981b07342)
![image](https://github.com/user-attachments/assets/8d5acc4e-958a-4384-9b0d-fa328a5abd19)
Вот

**Comment by LoveCaxarok** [comment]
@Kirlovon ииииии

**Comment by Kirlovon** [comment]
@LoveCaxarok Не могу найти подтверждения блокировки Kinobox в России, все должно работать. Расширение точно установлено правильно? Пробовали ли вы установить его в другом браузере?

**Comment by LoveCaxarok** [comment]
@Kirlovon Я как понял ,поговорив в чате ,наверное мой провайдер блокирует kinobox и админ сказал что сделал домен с прокси
S37:Замените в своем скрипте домен kinobox.tv на api.multy.plus
Сделаешь альтернавную версию скрипта?

**Comment by Kirlovon** [comment]
Я пока что не планирую делать альтернативную версию.

**Comment by 3d3d3d360** [comment]
Аналогичная ситуация, не работает ни в каком браузере. Показывает отсутствие фильма (из РФ).
Когда запустил на компьютере из другой страны, приложение заработало.
