### ISSUE TITLE
Запоминание выбора аудио-дорожки для сериала

### ISSUE THREAD

**Issue by TheYxel** [Kirlovon/Tape-Operator#52]
Помню что на старой платформе выбранный перевод переносился на следующую серию автоматом, а тут он на каждой следующей автоматом сбрасывается на первую.
Возможно ли релазивать данную фичу?
Не то чтобы это было как-то критично, Red Hat начали напрягать своими криками прямо посреди серии о том какие они молодцы.

**Comment by Kirlovon** [comment]
Я не отвечаю за разработку плееров, доступных через скрипт, поэтому не могу внести эти изменения.
