### ISSUE TITLE
Резко перестал работать.

### ISSUE THREAD

**Issue by Lomakinnn** [Kirlovon/Tape-Operator#54]
Резко перестал работать. Переустанавливал tampermonkey, скрипт, ставил tampermonkey legacy и соответственно скрипт на него, пробовал на разных браузерах (chrome, yandex), пробовал впн. С самим скриптом ничего не делал и не менял. На старых вкладках всё работает, на новых - нет.

**Comment by Kirlovon** [comment]
Что именно не работает? На каких вкладках он работает, а на каких нет?

**Comment by Chicha2k** [comment]
Ошибка при инициализации плеера на www.kinopoisk.ru:
Произошла ошибка во время инициализации плеера. Проверьте консоль разработчика и сообщите об ошибке по [этой ссылке ↗](https://github.com/Kirlovon/Tape-Operator/issues). Я постараюсь быстро все исправить! 🙂
Похоже что плеер так и не был инициализирован. Проверьте, установлена ли у вас актуальная версия скрипта [Tape Operator ↗](https://github.com/Kirlovon/Tape-Operator).
