### ISSUE TITLE
Не работает в разных браузерах

### ISSUE THREAD

**Issue by ImYukonRiver** [Kirlovon/Tape-Operator#55]
Добрый день!
Проблема такая: у нас дома три компьютера, на двух работает нормально, а на третьем ошибка. Пробовали браузеры chrome и opera. Какие нужно приложить скриншоты или логи, чтобы можно было идентифицировать проблему?
![image](https://github.com/user-attachments/assets/298f6e11-72ba-4887-ad80-5f20fb771820)

**Comment by ImYukonRiver** [comment]
При этом сам значок скрипта на странице с фильмом на кинопоиске есть, но при нажатии сначала очень долго грузится страница, а потом появляется вот эта ошибка

**Comment by BoiiScout** [comment]
![image](https://github.com/user-attachments/assets/d8bb27df-55ca-439a-8736-3d4b0898e386)
An error occurred during player initialization

**Comment by JonsonReggie51** [comment]
Начал выдавать ошибку: "Произошла ошибка во время инициализации плеера". Режим разработчика включён, как и раньше.

**Comment by Swell-I** [comment]
![изображение](https://github.com/user-attachments/assets/1425d8f2-94c5-4bd1-8eb7-459a4424da3f)

**Comment by fox9cat** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/4336e5f3-a407-4c89-b3dc-b8fa2a71dc33)
Режим разработчика включен, скрипт обновлен, переустановка темперманки и скрипта не помогли, с впн тоже не работает, в других браузерах тоже не работает. Мы соскучились по двум одинаковым рекламам каждые 10 минут, почините пожалуйста.

**Comment by BoiiScout** [comment]
Кто-то решил проблему?

сб, 7 дек. 2024 г., 18:21 fox9cat ***@***.***>:

**Comment by Kirlovon** [comment]
@ImYukonRiver @BoiiScout  @Swell-I  @fox9cat @JonsonReggie51 
Мне нужно увидеть консоль с логами, чтобы понять, что именно пошло не так. Пожалуйста, пришлите скриншот из консоли! Консоль можно открыть, нажав на странице с плеером правую кнопку мыши > Inspect > Console.

**Comment by Swell-I** [comment]
У меня все заработала ничего не трогал все само починилось
